# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MetalByTutorials' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'

  target 'MetalByTutorialsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MetalByTutorialsUITests' do
    # Pods for testing
  end

end
